### ISSUE TITLE
Need a reference genome file

### ISSUE THREAD

**Issue by zgtman** [matteo14c/CorGAT#1]
Hi,

first thank you for your tool. I tried couple of hours to solve problem with "need reference genome file in the current folder". 
My syntax is:
`perl annotate.pl --in consolidated_variant_calls --conf corgat.conf --out test`

```
cat corgat.conf 
genetic	genetic_code
genome	GCF_009858895.2_ASM985889v3_genomic.fna
annot	annot_table.pl
hyphy	hyphy_current.csv
AF	af_data_new.csv
MFE	MFE_annot.csv
EPI	epitopes_annot.csv
```
All those files are present in current folder including reference genome GCF_009858895.2_ASM985889v3_genomic.fna with write persmissions.

Any idea what is going wrong?

Best,
Paul

**Comment by matteo14c** [comment]
Dear Paul,

Thanks for spotting this. The "master" branch was not up to date and contained an older version of annotate.pl (with the name of the reference genome file hardcoded). Long story short, this was for facilitating comparisons and tracking of changes made to the code in the second run of peer-review of the tool. However, this is no longer needed. We have updated the master branch now. If you download again you should have no issues.
Please let us know.

cheers

Matteo

**Comment by zgtman** [comment]
Dear Matteo,

great thank you so much for update master. It is already works perfectly fine.
Thank you again for good tool.
Best,

Paul.
